@Host = https://localhost:5001

POST {{Host}}/execute-single-input
Content-Type: application/json

{
    "code": "using System; Console.WriteLine($\"{int.Parse(Console.ReadLine()) + int.Parse(Console.ReadLine())}\");",
    "input": "10\n8"
}
###

POST {{Host}}/execute-without-input
Content-Type: application/json

{
    "code": "using System; Console.WriteLine(\"Salom\");"
}